export const AppActions = {
  CREATE_TOURNAMENT: 'CREATE_TOURNAMENT',
  OPEN_TOURNAMENT: 'OPEN_TOURNAMENT',
  CLOSE_TOURNAMENT: 'CLOSE_TOURNAMENT',
  DELETE_TOURNAMENT: 'DELETE_TOURNAMENT',
  SET_INDEX_TAB: 'SET_INDEX_TAB',
  REFRESH_SUMMARIES: 'REFRESH_SUMMARIES',
}
